config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "main#index"
  get "/articles", to: "articles#index"
  get "/todos", to: "todos#index"


  resources :todos
  resources :articles do
    resources :comments
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy

    validates :title, presence: true 
    validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end
  
    def archived?
      status == 'archived'
    end
  end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "default", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show 
    @article = Article.find(params[:id])
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#    http_basic_authenticate_with name: "default", password: "password", only: :destroy
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)
  
    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
  
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_container") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message |%>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status %>
        <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h2> Edit </h2>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="max-w-3xl mx-auto bg-white p-8 shadow-lg">
  <div class="mb-8">
    <h1 class="text-4xl font-bold mb-4">Articles</h1>
    <p class="italic mb-8">
      This blog has
      <strong class="font-semibold"><%= Article.public_count %></strong>
      articles and counting!
    </p>
  </div>
  <div class="mb-8">
    <ul>
      <% @articles.each do |article| %>
        <% unless article.archived? %>
          <li class="mb-2 bg-gray-300 px-4 py-2 rounded hover:bg-gray-500">
            <%= link_to article.title, article, class: "text-indigo-700 hover:text-indigo-900" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div>
    <ul>
      <li class="mb-2 bg-green-300 px-4 py-2 rounded hover:bg-green-500">
        <%= link_to "New Article", new_article_path, class: "text-slate-900 hover:text-indigo-900" %>
      </li>
      <li class="bg-orange-300 px-4 py-2 rounded hover:bg-orange-500">
        <%= link_to "Home", root_path, class: "text-slate-900 hover:text-indigo-900" %>
      </li>
    </ul>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="max-w-3xl mx-auto bg-white p-8 shadow-lg">

 <h1 class="text-4xl font-bold mb-4"><%= @article.title %></h1>
 <p class="mb-8"><%= @article.body %></p>

 <ul class="mb-8">
   <li class="mb-2 bg-blue-300 px-4 py-2 rounded hover:bg-blue-500">
     <%= link_to "Edit", edit_article_path(@article), class: "text-slate-900 hover:text-indigo-900" %>
   </li>
   <li class="mb-2 bg-blue-300 px-4 py-2 rounded hover:bg-blue-500">
     <%= link_to "Destroy", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "For real?" }, class: "text-slate-9800 hover:text-indigo-900" %>
   </li>
   <li class="mb-2 bg-blue-300 px-4 py-2 rounded hover:bg-blue-500">
     <%= link_to "Index", root_path, class: "text-slate-900 hover:text-indigo-900" %>
   </li>
 </ul>

  <h3 class="text-2xl font-semibold mb-4">Comments</h3>
  <%= render @article.comments %>
  <h3 class="text-2xl font-semibold mt-8 mb-4">Add a comment:</h3>
  <%= render 'comments/form' %>

</div>

app/views/comments/_comment.html.erb
<div class="max-w-3xl mx-auto bg-white p-8 shadow-lg">
 <% unless comment.archived? %>
   <p class="mb-4">
     <strong class="font-semibold">Commenter:</strong> <%= comment.commenter %><br>
     Comment: <i><%= comment.body %></i>
   </p>
   <p class="mb-2 bg-blue-300 px-4 py-2 rounded hover:bg-blue-500">
     <%= link_to "Destroy Comment", [comment.article, comment], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-slate-900 hover:text-indigo-900" %>
   </p>
 <% end %>
</div>

app/views/comments/_form.html.erb
<div class="max-w-3xl mx-auto bg-white p-8 shadow-lg">
 <%= form_with model: [@article, @article.comments.build], class: "bg-gray-100 p-6 rounded" do |form| %>
   <div class="mb-4">
     <%= form.label :commenter, class: "font-semibold mb-1 block" %><br>
     <%= form.text_field :commenter, class: "border border-gray-400 p-2 w-full rounded" %>
   </div>
   <div class="mb-4">
     <%= form.label :body, class: "font-semibold mb-1 block" %><br>
     <%= form.text_area :body, class: "border border-gray-400 p-2 w-full rounded" %>
   </div>
   <div class="mb-4">
     <%= form.label :status, class: "font-semibold mb-1 block" %><br>
     <%= form.select :status, Visible::VALID_STATUSES, { selected: 'public' }, { class: "border border-gray-400 p-2 w-full rounded" } %>
   </div>
   <div class="mb-2 bg-blue-300 px-4 py-2 rounded hover:bg-blue-500">
     <%= form.submit class: "text-slate-900 hover:text-indigo-900" %>
   </div>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAppArtyom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex bg-gray-50">
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<div class="relative flex h-full w-screen flex-col justify-center overflow-hidden bg-gray-50 py-6 sm:py-12">
 <div id="content" class="mx-auto w-4/5 bg-slate-300 bg-center p-6">
   <div class="mx-auto max-w-xl bg-gray-50 p-12 shadow-lg">
     <h1 class="w-96 h-32 box-decoration-slice bg-gradient-to-r from-indigo-600 to-pink-500 text-slate-100 p-4 text-6xl text-center">It's Rails</h1>
   </div>
   <hr class="my-12">
   <div class="mx-auto bg-gray-50 p-12 shadow-lg">
     <ul class="inline text-3xl underline">
       <li class="text-indigo-900 mr-8 p-2"><%= link_to "Blog", articles_path %></li>
       <li class="text-indigo-900 mr-8 p-2"><%= link_to "Todos", todos_path %></li>
     </ul>
   </div>
 </div>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex items-stretch flex-grow">
    <%= form.label :name, class: "sr-only" %>
    <%= form.text_field :name, class: "block w-full rounded-none rounded-l-md sm:text-sm border-gray-300", placeholder: "Add a new todo..." %>
    <%= form.submit class: "-ml-px relative px-4 py-2 border border-blue-600 text-sm font-medium rounded-r-md text-white bg-blue-600 hover:bg-blue-700" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<li class="py-2 px-4 border-b border-gray-300" id="<%= "#{dom_id(todo)}_container" %>">

  <div class="flex justify-between items-center space-x-2">
    <%= todo.name %>
     <%= button_to todo_path(todo), class: "bg-blue-300 px-4 py-2 rounded hover:bg-blue-500", method: :delete do %>
        <span><p class="color-slate-900">Done</p></span>
      <% end %>
  </div>
</li>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<div class="mx-auto w-2/3 bg-gray-50">
  <div>
    <p class="text-green-500"><%= notice %></p>
    <h1 class="text-4xl font-bold text-indigo-600 mb-8">Your Todos</h1>
  </div>

  <div class="grid grid-cols-1 gap-8 py-8 px-12 border rounded shadow-md">
    <ul id="todos">
      <%= render @todos %>
    </ul>
  </div>
  <div>
    <ul class="mt-8">
      <li class="mb-2">
        <%= link_to "New todo", new_todo_path, class: "text-indigo-600 hover:text-indigo-900" %>
      </li>
      <li>
        <%= link_to "Home", root_path, class: "text-indigo-600 hover:text-indigo-900" %>
      </li>
    </ul>
  </div>
</div>

app/views/todos/new.html.erb
<div>
  <div>
    <h1>New todo</h1>

 
    <hr>

    <div class="grid grid-cols-1 gap-8 py-8 px-12 border rounded shadow-md">
         <%= render "form", todo: @todo %>
         <%= link_to "Back to todos", todos_path, class: "-ml-px relative px-4 py-2 border border-green-600 text-sm rounded font-medium text-white bg-green-600 hover:bg-blue-700" %>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>